stages:
  load_data:
    cmd: python -m src.load_data
    deps:
      - src/load_data.py
    outs:
      - out/dataset.tsv
  preprocess:
    cmd: python -m src.preprocess
    deps:
      - out/dataset.tsv
      - src/preprocess.py
      - src/helper.py
    outs:
      - out/c1_BoW_Sentiment_Model.pkl
      - out/preprocessed.joblib
  train_model:
    cmd: python -m src.model
    deps:
      - out/preprocessed.joblib
      - out/dataset.tsv
      - src/model.py
      - src/helper.py
    outs:
      - out/c2_Classifier_Sentiment_model.joblib
    metrics:
      - summary.json:
          cache: false
