stages:
  preprocess:
    cmd: python src/preproccesing_dataset.py
    deps:
    - a1_RestaurantReviews_HistoricDump.tsv
    - src/preproccesing_dataset.py
    outs:
    - out/c1_BoW_Sentiment_Model.pkl
    - out/preprocessed.joblib
  train_model:
    cmd: python src/train_model.py
    deps:
    - a1_RestaurantReviews_HistoricDump.tsv
    - out/preprocessed.joblib
    - src/train_model.py
    outs:
    - out/c2_Classifier_Sentiment_model.joblib