stages:
  preprocess:
    cmd: python -m src.preprocess
    deps:
      - a1_RestaurantReviews_HistoricDump.tsv
      - src/preprocess.py
      - src/helper.py
    outs:
      - out/c1_BoW_Sentiment_Model.pkl
      - out/preprocessed.joblib
  train_model:
    cmd: python -m src.model
    deps:
      - a1_RestaurantReviews_HistoricDump.tsv
      - out/preprocessed.joblib
      - src/model.py
      - src/helper.py
    outs:
      - out/c2_Classifier_Sentiment_model.joblib
    metrics:
      - summary.json:
          cache: false
