name: Automated Testing

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: coverage run --source=src -m pytest -v tests && coverage report -m

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
