name: Linters

on: [pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install pylint dslinter mllint

      - name: Run pylint
        run: pylint --load-plugins=dslinter src/

      - name: Run mllint
        run: mllint
